name: Trigger auto deployment for duda-teste-lobe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/duda-teste-lobe-AutoDeployTrigger-fb05636f-0375-40ce-ad15-c579309a830d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DUDATESTELOBE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DUDATESTELOBE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DUDATESTELOBE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.DUDATESTELOBE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DUDATESTELOBE_REGISTRY_PASSWORD }}
          containerAppName: duda-teste-lobe
          resourceGroup: dev-duda
          imageToBuild: eduardafs/duda-teste-lobe:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


